baseURL = "https://backsteinexpressionismus.projektemacher.org/"
languageCode = "de"
title = "Backsteinexpressionismus"
publishDir = "docs"
canonifyurls = true
languagecode = "de"
defaultcontentlanguage = "de"
rssLimit = 25
Paginate = 20
disablePathToLower = true
theme = ["projektemacher-base"]
copyright = '<a href="https://projektemacher.org/" target="_blank">Projektemacher</a>'

[menu]
    [[menu.main]]
        name = "Start"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Übersichten"
        url = "/lists"
        weight = 1

    [[menu.main]]
        name = "Links"
        url = "/links"
        weight = 2

    [[menu.main]]
        name = "Über"
        url = "/about"
        weight = 3

[module]
    [[module.mounts]]
        source = "assets/scss"
        target = "assets/scss"

    [[module.mounts]]
        source = "assets/js"
        target = "assets/js"

    [[module.mounts]]
        source = "static"
        target = "static"

[mediaTypes]
  [mediaTypes."application/json"]
    suffixes = ["geojson", "gjson"]

[outputFormats]
  [outputFormats.geojson]
    mediaType = "application/json"
    isPlainText = true
    isHTML = false
    baseName = "map"
    notAlternative = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe= true

[imaging]
    quality = 95

[taxonomies]
  tag = "tags"
