baseURL = "https://backsteinexpressionismus.projektemacher.org/"
languageCode = "de"
title = "Backsteinexpressionismus"
publishDir = "docs"
canonifyurls = true
languagecode = "de"
defaultcontentlanguage = "de"
rssLimit = 25
Paginate = 20
disablePathToLower = true
theme = ["projektemacher-base"]

[params]
    author = "Christian Mahnke"
    homeTitle = "Backsteinexpressionismus"
    header = "/images/header.svg"
    description = "Alte Abbildungen von Backsteinexpressionismus-Gebäuden aus Büchen und von Postkarten."
    keywords = "Backsteinexpressionismus, Architektur, Bücher, Postkarten, Brickexpressionism, Acrhitecture, Books, Postcards"
    stylesheets = []
    copyright = "MMXXI"
    productionIIIFURLPrefix="https://static.projektemacher.org/backsteinexpressionismus/"

[menu]
    [[menu.main]]
        name = "Start"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Übersichten"
        url = "/lists"
        weight = 1

    [[menu.main]]
        name = "Über"
        url = "/about"
        weight = 2

[module]
    [[module.mounts]]
        source = "assets/scss"
        target = "assets/scss"

    [[module.mounts]]
        source = "assets/js"
        target = "assets/js"

    [[module.mounts]]
        source = "static"
        target = "static"

[mediaTypes]
  [mediaTypes."application/json"]
    suffixes = ["geojson", "gjson"]

[outputFormats]
  [outputFormats.GEOJSON]
    mediaType = "application/json"
    isPlainText = true
    isHTML = false
    baseName = "map"
    notAlternative = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe= true

[imaging]
    quality = 95

[taxonomies]
  tag = "tags"
