baseURL = "http://example.org/"
languageCode = "de"
title = "Backsteinexpressionismus"
publishDir = "docs"
canonifyurls = true
languagecode = "de"
defaultcontentlanguage = "de"
rssLimit = 25
#theme = "projektemacher-base"


[params]
    author = "Christian Mahnke"
    homeTitle = "Backsteinexpressionismus"
    description = ""
    keywords = ""
    #stylesheets = ["https://fontlibrary.org/face/futura-renner"]
    stylesheets = []

[menu]
    [[menu.main]]
        name = "Start"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Über"
        url = "/about"
        weight = 2

[module]
    [[module.mounts]]
        source = "assets/scss"
        target = "assets/scss"

    [[module.mounts]]
        source = "assets/js"
        target = "assets/js"

    [[module.mounts]]
        source = "static"
        target = "static"

    [[module.mounts]]
        source = "node_modules/ol"
        target = "assets/css/ol"

    [[module.mounts]]
        source = "node_modules/normalize.css"
        target = "assets/css/normalize"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe= true

[imaging]
    quality = 95
