baseURL = "http://example.org/"
languageCode = "de"
title = "Backsteinexpressionismus"
publishDir = "docs"
canonifyurls = true
languagecode = "de"
defaultcontentlanguage = "de"
rssLimit = 25

[params]
    author = "Christian Mahnke"
    homeTitle = "Backsteinexpressionismus"
    description = ""
    keywords = ""

[module]
    [[module.mounts]]
        source = "assets/scss"
        target = "assets/scss"

    [[module.mounts]]
        source = "assets/js"
        target = "assets/js"

    [[module.mounts]]
        source = "static"
        target = "static"

    [[module.mounts]]
        source = "node_modules/ol"
        target = "assets/css/ol"


[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe= true
